version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: hom-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hom
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hom-backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/hom
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hom-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"
